---
description :
    name : hashtags_per_page
    full description : Returns the most frequently occurring hashtags in comments in the last published posts of a Facebook page.
parameters :
    required :
        - name : fb_page_id
          type : string
          description : 'The facebook page identifier'
    optional :
        - name : since
          type : int
          description : 'Starting Analyse time. Default value is yesterday'
        - name : until
          type : int
          description : 'Ending Analyse time. Default value is now'
        - name : limit
          type : int
          description : 'Maximum number of posts to analyse'
tools :
    - facebook_token_handler
...
