---
description :
    name : metrics_per_post
    full description : Returns all the metrics (likes,comments number,love,haha,...) of a Facebook post.
parameters :
    required :
        - name : fb_post_id
          type : string
          description : 'The facebook post identifier'
tools :
    - facebook_token_handler
...
